version: "3"
services:
  web:
    build: 
      context: .
    restart: always
    env_file:
      - ./.env
    command: gunicorn --bind 0.0.0.0:8000 app.wsgi --reload
    ports:
      - "8000:8000"
    links:
      - redis:redis
    depends_on:
      - nginx
      - db
      - celery
    networks:
      - main
    volumes:
      - ./app:/app
      - ./media:/vol/web/media
      - ./static:/vol/web/static
  nginx:
    image: "nginx"
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./media:/vol/web/media
      - ./static:/vol/web/static
    ports:
      - "80:80"
    networks:
      - main
  redis:
    restart: always
    image: redis:latest
    expose:
      - "6379"
    networks:
      - main
  db:
    image: postgres
    ports: 
      - "5432:5432"
    networks:
      - main
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  celery:
    build: .
    restart: unless-stopped
    command: celery -A app worker -l info
    # volumes:
    #   - .:/app
    depends_on:
      - db
      - redis
    networks:
      - main
    env_file:
      - ./.env
  celery-beat:
    build: .
    restart: unless-stopped
    command: celery -A app beat -l info   
    # volumes:
    #   - .:/app
    depends_on:
      - db
      - redis
    networks:
      - main
    env_file:
      - ./.env
networks:
  main:
volumes:
  postgres_data: