version: "3"

services:  
  elasticsearch:
    image: elasticsearch:7.5.1

    volumes:
      - ./data:/usr/share/elasticsearch/data
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      # - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    # networks:
    #   - elastic
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "
      python manage.py wait_for_db &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000 "
    # environment:
    #   - DB_HOST=db
    #   - DB_NAME=dev
    #   - DB_USER=postgres
    #   - DB_PASS=supersecretpassword
    depends_on:
      - elasticsearch



#   db:
#     image: postgres
#     environment:
#       - POSTGRES_DB=dev
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=supersecretpassword
#     volumes:
#       - postgres_dev_data:/var/lib/postgresql/data/

volumes:
  data:
    
# networks:
#   elastic:
#     driver: bridge